version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_todolist
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./var/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: todolist